 
post_install()
{
    xdg-icon-resource install --context apps --size 16 /usr/share/pixmaps/paraview.png kitware-paraview
    update-desktop-database -q
}

post_upgrade()
{
    xdg-icon-resource install --context apps --size 16 /usr/share/pixmaps/paraview.png kitware-paraview
    update-desktop-database -q
}
pre_remove()
{
    xdg-icon-resource uninstall --context apps --size 16 /usr/share/pixmaps/paraview.png kitware-paraview
}
post_remove()
{
    update-desktop-database -q
}
